name: CI with Docker for Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Create Docker network
      - name: Create Docker network
        run: docker network create ci-network

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build -t nextjs-app-ci .

      # Step 5: Run Jest tests inside the Docker container
      - name: Run Jest tests
        run: docker run --rm nextjs-app-ci npm test

      # Step 6: Start the Next.js app in Docker on the custom network
      - name: Start Next.js app in Docker (for Cypress)
        run: |
          docker run -d --rm \
            --network ci-network \
            --network-alias app \
            --name nextjs-app \
            nextjs-app-ci npm run dev -- -H 0.0.0.0

      # Step 7: Wait on server
      - name: Wait on server
        run: |
          max_retries=10
          count=0
          until docker run --rm --network ci-network appropriate/curl curl -f http://app:3000; do
            sleep 5
            count=$((count + 1))
            if [ $count -ge $max_retries ]; then
              echo "Next.js app did not become ready in time."
              exit 1
            fi
          donet 1

      # Step 8: Run Cypress tests
      - name: Run Cypress tests
        run: |
          docker run --rm --network ci-network \
            -v ${{ github.workspace }}:/e2e \
            --workdir=/e2e \
            cypress/included:13.15.0 \
            cypress run --config baseUrl=http://app:3000

      # Step 9: Stop Next.js app
      - name: Stop Next.js app
        run: docker stop nextjs-app

      # Step 10: Clean up Docker network
      - name: Clean up Docker network
        run: docker network rm ci-network
